# Generated by Django 5.2.1 on 2025-05-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automacao',
            name='porcentagem',
            field=models.IntegerField(default=0),
        ),
    ]
